### ISSUE TITLE
Docusaurus build fails when "trailingSlash: false"

### ISSUE THREAD

**Issue by sdirix** [easyops-cn/docusaurus-search-local#100]
Hi! Recently the Docusaurus team introduced a new configuration option `trailingSlash: boolean | undefined`, see [here](https://docusaurus.io/docs/docusaurus.config.js/#trailing-slash).

When specifying `trailingSlash: false` and using `"@easyops-cn/docusaurus-search-local": "^0.16.3"` the Docusaurus build breaks. You can reproduce the issue on [this branch](https://github.com/sdirix/jsonforms2-website/tree/trailing-slash-false).

>Unable to build website for locale "en".
>Error: ENOENT: no such file or directory, open 'path/build/docs/index.html'

**Comment by slorber** [comment]
+1

We got this reported to the main Docusaurus repo too: https://github.com/facebook/docusaurus/issues/5267

If that helps, here's the logic we use to emit HTML files:

https://github.com/slorber/static-site-generator-webpack-plugin/blob/master/index.js#L167

```js
function pathToAssetName(outputPath, preferFoldersOutput) {
  var outputFileName = outputPath.replace(/^(\/|\\)/, ''); // Remove leading slashes for webpack-dev-server

  // Paths ending with .html are left untouched
  if (/\.(html?)$/i.test(outputFileName)) {
    return outputFileName;
  }

  // Legacy retro-compatible behavior
  if (typeof preferFoldersOutput === 'undefined') {
    return path.join(outputFileName, 'index.html');
  }

  // New behavior: we can say if we prefer file/folder output
  // Useful resource: https://github.com/slorber/trailing-slash-guide
  if ( outputPath === "" || outputPath.endsWith("/") || preferFoldersOutput ) {
    return path.join(outputFileName, 'index.html');
  }
  else {
    return `${outputFileName}.html`;
  }
}
```

You can consider `preferFoldersOutput === siteConfig.trailingSlash`

Eventually, it may be safer (probably also less performant :s) to test for the file to exist here: https://github.com/easyops-cn/docusaurus-search-local/blob/a7b1b3a98bda9c72859ebc762efa5eb874dbd7e9/src/server/utils/processDocInfos.ts

**Comment by weareoutman** [comment]
@slorber Thanks, that seems would help a lot, I will look into it later.

> BTW, I'd like to have a docusaurus-community org (still waiting for FB approval), and move existing popular community plugins to it so that they can be more easily maintained, let me know if you would be ok with that. Having admin access on Github/NPM would allow me to keep the code in sync with Docusaurus core and ensure there's no such issues (or at least I'll be able to fix them rapidly)

This sounds good, and I am personally ok with that. Although this plugin is maintained by myself, but the ownership of this project belongs to my company, so it needs approval. Let me know when the docusaurus-community gets progressed, I'd like to help.

**Comment by weareoutman** [comment]
@sdirix try "@easyops-cn/docusaurus-search-local": "^0.19.0"

**Comment by slorber** [comment]
Thanks :) will try to get this org setup but it's not my decision and it may take some additional time. Will ping plugin authors once we have it
