### ISSUE TITLE
Content under initial # in a docs page is not found

### ISSUE THREAD

**Issue by andrewsnowden** [easyops-cn/docusaurus-search-local#109]
In a markdown page, if I add content directly underneath the top level heading then it does not appear in the search results. For example, if I have a markdown page like:

```
# My title

Search below title

## Subtitle

Search below subtitle
```

I then search for the word "search" and it will only show me one result which is the "Search below subtitle" line. 

I verified this with a brand new blank Docusaurus install, adding the search plugin and putting some content directly under a title. I can attach the example project if that will be helpful.

Thanks for the great project!

**Comment by Lytsu** [comment]
It may be that your markdown document is recognized as **Pages** instead of **Documents**, try adding `indexPages:true` to the plugin options.
```
plugins: [
            '@easyops-cn/docusaurus-search-local',
            {
              // `hashed` is recommended as long-term-cache of index file is possible.
              hashed: true,
              // For Docs using Chinese, The `language` is recommended to set to:
              language: ["en", "zh"],
              // When applying `zh` in language, please install `nodejieba` in your project
              highlightSearchTermsOnTargetPage: false,
              indexDocs:true,
              indexPages:true,
            },
]
```

**Comment by weareoutman** [comment]
I think this is fixed by recent updates. Please try latest `@easyops-cn/docusaurus-search-local` with latest `docusaurus`.
