### ISSUE TITLE
Search text not visible on Search Page in dark mode

### ISSUE THREAD

**Issue by kslean** [easyops-cn/docusaurus-search-local#125]
Steps to reproduce:
1) Open the website with the plug-in installed, in dark mode.
2) Enter a search word into the search field.
3) Select the See all results option

In the search field at the top of the search page, both the text and the background of the field at white.

Expect: In dark mode, I expect the background of the search field to be dark, similar to the look of the search field in the nav bar.

**Comment by weareoutman** [comment]
I can't reproduce it, can you provide some environment information, such as what system and browser you're using?
![image](https://user-images.githubusercontent.com/2338946/144963471-de80dff0-762c-4dae-a643-291667c80116.png)

**Comment by weareoutman** [comment]
> Expect: In dark mode, I expect the background of the search field to be dark, similar to the look of the search field in the nav bar.

This sounds reasonable. I'll try to fix it.

**Comment by weareoutman** [comment]
Thanks for your reporting. It is released in v0.21.1.
