### ISSUE TITLE
Incorrect shortcut styling for dark-only navbar

### ISSUE THREAD

**Issue by sisp** [easyops-cn/docusaurus-search-local#128]
The shortcut feature added by https://github.com/easyops-cn/docusaurus-search-local/pull/111 styles the search hint (`CTRL+K`) incorrectly when the [navbar style](https://docusaurus.io/docs/api/themes/configuration#navbar-style) is "dark":
![image](https://user-images.githubusercontent.com/2206639/145707334-8a37090e-8323-46f9-b79b-f3117de0cb9f.png)

**Comment by weareoutman** [comment]
Fixed in v0.21.2.

**Comment by sisp** [comment]
Awesome, thank you very much!
