### ISSUE TITLE
Suggestions overlay partially outside viewport

### ISSUE THREAD

**Issue by sisp** [easyops-cn/docusaurus-search-local#135]
The suggestions overlay is partially outside the viewport (on the left) on small screens:
![image](https://user-images.githubusercontent.com/2206639/146200230-d6a4a1b4-c7d6-4c5a-a39a-3c903c8b994a.png)

I think the overlay's maximum width should be limited to the width of the viewport (minus the horizontal margins). Perhaps using `max-width: 100%`?

**Comment by weareoutman** [comment]
Yes, we should use a `max-width`. Fixed in v0.21.4.

**Comment by sisp** [comment]
That was quick! However, I don't think the fix is fully correct:
![image](https://user-images.githubusercontent.com/2206639/146212553-82d20f20-eea5-4e59-bbb7-47f96941d0bd.png)
The margin on the left and right is not the same.

**Comment by weareoutman** [comment]
Um, that's weird. Is there any reproducible link? It works in my [example site](https://easyops-cn.github.io/docusaurus-search-example/) when simulating a small screen:

![image](https://user-images.githubusercontent.com/2338946/146218803-aa734fe3-7403-4eed-b5e2-1118ec4620ac.png)

**Comment by sisp** [comment]
Not with v0.21.4, I've taken a screenshot of the locally updated site https://mobx-keystone.js.org, but it's not published anywhere with this version.

But I've noticed it works when I simulate a mobile device in the browser like you did, but when I don't enable this mode but just make the desktop browser window narrow, it looks like on my screenshot. So there seems to be a difference between the simulated mobile device mode and the regular desktop mode. :thinking: Can you confirm that it doesn't work when you just make your regular desktop browser window narrow?

**Comment by weareoutman** [comment]
I can't make my browser window narrow than about 500px, so I can't reproduce your problem.

I tried Chrome and Safari on Mac. What's your browser and system? And have you tried on real phone with small screen?

**Comment by sisp** [comment]
I just Firefox and Chromium on Ubuntu 18.04. For making the window narrower than 500px, I open the developer tools (F12) and make their view wide and thus the website content view narrow.

**Comment by weareoutman** [comment]
I still can't reproduce it, even if I narrowed it to less than 300px.

I think it's ok even though it maybe not 100 perfect on certain circumstances, but at least no content was cropped, :)

![image](https://user-images.githubusercontent.com/2338946/146385158-7eff88db-c559-4ce2-aae6-82956d564045.png)

**Comment by sisp** [comment]
Would you mind giving this one last try with the project documentation from which I've taken the screenshots?

```bash
git clone git@github.com:xaviergonz/mobx-keystone.git
cd mobx-keystone/
yarn install --immutable
cd packages/site/
yarn add @easyops-cn/docusaurus-search-local@^0.21.4
cd ../..
yarn build-netlify
yarn site:serve
```

Can you reproduce it now?
