### ISSUE TITLE
Use wasm version of `jieba` to avoid build `nodejieba`

### ISSUE THREAD

**Issue by Airkro** [easyops-cn/docusaurus-search-local#140]
Install `nodejieba` is painful.

Maybe: `nodejieba` -> https://github.com/napi-rs/node-rs/tree/main/packages/jieba

**Comment by F3n67u** [comment]
+1, install nodejieba is very slow.

**Comment by weareoutman** [comment]
Looks good and will look at it later once I got time. Or anyone can help with a PR, that is welcome.

**Comment by weareoutman** [comment]
Thanks for @F3n67u 's work, released in v0.23.0!
