### ISSUE TITLE
Search page not working

### ISSUE THREAD

**Issue by dkobran** [easyops-cn/docusaurus-search-local#143]
I'm testing out this plugin. It works really well except on the search modal, when you click "see all results," you are taken to a page that appears to not work. If you type anything on this [page](https://psdocs.netlify.app/search/) in the search box, nothing is returned whereas the nav bar version works. 

1. Is this a known issue? 
2. In the meantime, would it be possible to hide this option?

Here is my draft site: https://psdocs.netlify.app

yarn list:
```
yarn list v1.22.17
├─ @docusaurus/core@2.0.0-beta.14
├─ @docusaurus/cssnano-preset@2.0.0-beta.14
├─ @docusaurus/logger@2.0.0-beta.14
├─ @docusaurus/mdx-loader@2.0.0-beta.14
├─ @docusaurus/plugin-content-blog@2.0.0-beta.14
├─ @docusaurus/plugin-content-docs@2.0.0-beta.14
├─ @docusaurus/plugin-content-pages@2.0.0-beta.14
├─ @docusaurus/plugin-debug@2.0.0-beta.14
├─ @docusaurus/plugin-google-analytics@2.0.0-beta.14
├─ @docusaurus/plugin-google-gtag@2.0.0-beta.14
├─ @docusaurus/plugin-sitemap@2.0.0-beta.14
├─ @docusaurus/preset-classic@2.0.0-beta.14
├─ @docusaurus/react-loadable@5.5.2
├─ @docusaurus/theme-classic@2.0.0-beta.14
├─ @docusaurus/theme-common@2.0.0-beta.14
├─ @docusaurus/theme-search-algolia@2.0.0-beta.14
├─ @docusaurus/theme-translations@2.0.0-beta.14
├─ @docusaurus/utils-common@2.0.0-beta.14
├─ @docusaurus/utils-validation@2.0.0-beta.14
├─ @docusaurus/utils@2.0.0-beta.14
├─ @easyops-cn/autocomplete.js@0.38.1
└─ @easyops-cn/docusaurus-search-local@0.21.4
```

node version: v16.13.2

Thanks!

**Comment by dkobran** [comment]
I had algolia added to docusaurus.config.js which was causing issues. All set! May be worth adding to the readme that this conflicts with your plugin.

**Comment by ivonGwy** [comment]
i met the same issue, has no query result  only on page /search?q= ,
i used the preset-classic theme ,didnt config anything about algolia 
how did you solve your issue?
