### ISSUE TITLE
root index.html is not indexed in docs only mode

### ISSUE THREAD

**Issue by pranabdas** [easyops-cn/docusaurus-search-local#145]
In a docs-only site (`routeBasePath: "/"`), I have a page with slug `/`, which produces an `index.html` in the root build directory. Looks like this root `index.html` in not indexed, every other page is working as intended. I have following option for `@easyops-cn/docusaurus-search-local`:
```
themes: [
      [
        require.resolve("@easyops-cn/docusaurus-search-local"),
        {
          hashed: true,
          docsRouteBasePath: "/",
          indexBlog: false,
          indexPages:true,
          highlightSearchTermsOnTargetPage: true,
        },
      ],
    ],
```

Thank you.

**Comment by arifszn** [comment]
+1. Having the same issue.

**Comment by yumengzhong** [comment]
+1. Having the same issue.
