### ISSUE TITLE
Specify search results as current version

### ISSUE THREAD

**Issue by Yunkou** [easyops-cn/docusaurus-search-local#150]
👋 ，
When I use multiple versions to manage documents, the search results bring up all the version results.
The expectation is to add parameters to `Theme Options` to specify it as the current version.
For example:  `currentVersion` `boolean`  `false` ` to specify search results as the current version.` 
Many thanks! 🙏

**Comment by hijulien-gan** [comment]
I also need this function

**Comment by weareoutman** [comment]
This is supported since v0.27.0. Notice there is [an issue](#203) with it although.
