### ISSUE TITLE
Warning `Overwriting existing registered function: lunr-multi-trimmer-en-zh`

### ISSUE THREAD

**Issue by ApsarasX** [easyops-cn/docusaurus-search-local#155]
My Config is as shown below.

```
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        language: ['en', 'zh']
      }
    ]
```

<img width="633" alt="image" src="https://user-images.githubusercontent.com/24390069/159476998-c32e8529-1d6b-466a-9c82-cfba1d5a8c38.png">

**Comment by ApsarasX** [comment]
> 

The config of `docusaurus-search-local` is in the `theme` is indeed.😂

This is the `docusaurus.config.js` of my blog.

https://github.com/ApsarasX/blog/blob/619da4e1db998b182024a2ce90298eaf80ae9d0d/docusaurus.config.js#L60-L73

**Comment by weareoutman** [comment]
You can safely dismiss this warning.

**Comment by o-l-a-v** [comment]
The fix has been discussed in:

* This issue: <https://github.com/olivernn/lunr.js/issues/339>
* This comment: <https://github.com/olivernn/lunr.js/issues/339#issuecomment-383384960>

Seems this is fixed by:

> Have you tried lifting the call to `lunr.multiLanguage` out of the regeneration function in order to call it once, and passing its return value to `this.use`?

Code example from the comment:

```javascript
"use strict";

const lunr = require("lunr");
require("lunr-languages/lunr.stemmer.support")(lunr);
require("lunr-languages/lunr.multi")(lunr);
require("lunr-languages/lunr.it")(lunr);

let englishItalianSupport = lunr.multiLanguage('en', 'it'); // here

// > Access to the index for full text search
let fullTextIndex;

// > Generate the index for full text search
exports.regenerateFullTextIndex = function(documents) {

   fullTextIndex = lunr(function() {

      this.use(englishItalianSupport); // ...and here

      this.ref("id");
      this.field("title");
      this.field("body");

      const len = documents.length;
      for(let i = 0; i < len; ++i) {
         this.add({id: documents[i].id, title: documents[i].title, body: documents[i].text});
      }
   });
};
```

---

@weareoutman: Please fix?
