### ISSUE TITLE
Proposal: on board to Docusaurus i18n system

### ISSUE THREAD

**Issue by Josh-Cena** [easyops-cn/docusaurus-search-local#160]
Hi, Docusaurus maintainer here!

I noticed you are using a custom translation system: https://github.com/easyops-cn/docusaurus-search-local#translations

Docusaurus now has its own i18n system, which is not too much deviated from what you have, but what's nice is that (a) you can provide OOTB theme translations and (b) users can see all text labels that need to be translated simply by running `yarn write-translations`.

I can't find any relevant discussion on this, so do you have plans about onboarding to the Docusaurus i18n system?

**Comment by weareoutman** [comment]
Thanks for reminding, there is a conversation about this on [a stale PR](https://github.com/easyops-cn/docusaurus-search-local/pull/65#discussion_r607427130). However I can't squeeze in some time to make it onboard, yet :(
