### ISSUE TITLE
Search page is not working with versioned docs

### ISSUE THREAD

**Issue by weareoutman** [easyops-cn/docusaurus-search-local#203]
The search bar is working great with versioned docs since v0.27.0, however, the search page is not.

Repro:

1. Open the [*next* version of the example website](https://easyops-cn.github.io/docusaurus-search-local/docs/next/intro/).
2. Click the search bar and enter `intro`.
3. Click the link `See all results` below.
4. Shows `Page not found`.

cc @Cyriuz

**Comment by Cyriuz** [comment]
Forgot about that one, sorry, will take a look!
