### ISSUE TITLE
"Previous" and "Next" page names are considered as search results

### ISSUE THREAD

**Issue by raamcosta** [easyops-cn/docusaurus-search-local#204]
If I search for a page heading, I always get results from the previous and next pages since they mention the search term as the "next" and "previous" links respectively.

Is there any way to ignore particular sections of the page?

**Comment by weareoutman** [comment]
I can't reproduce your problem on our [example website](https://easyops-cn.github.io/docusaurus-search-local/), can you share a reproduction?

**Comment by raamcosta** [comment]
Sure!
This is already live here:
https://composedestinations.rafaelcosta.xyz/
(Github proj: https://github.com/raamcosta/compose-destinations-docs)

I'm using this config:
```
{
          indexPages: true,
          indexBlog: false,
          removeDefaultStopWordFilter: true,
          removeDefaultStemmer: true,
          highlightSearchTermsOnTargetPage: true,

          // `hashed` is recommended as long-term-cache of index file is possible.
          hashed: true,
        },
```

**Comment by raamcosta** [comment]
Also @weareoutman is there a way to order search results? I was thinking it would be nice to have matching headings at the top, and matches on normal text, below.

**Comment by weareoutman** [comment]
Try configure this theme correctly:

```diff
- indexPages: true,
+ docsRouteBasePath: "/",
```

See our readme:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/2338946/170966537-392ae762-2f6f-4969-b578-2f1b65c648b5.png">

**Comment by raamcosta** [comment]
Ahh that may be it 🙂 Thanks!

**Comment by raamcosta** [comment]
I missed the docs only thing 👍

**Comment by weareoutman** [comment]
👍. Maybe we can improve it by autodetecting docs-only mode in future.
