### ISSUE TITLE
Docusaurus Build fails when all @docusaurus/plugin-content-docs instances have custom ids

### ISSUE THREAD

**Issue by noobinthisgame** [easyops-cn/docusaurus-search-local#211]
Hi,

when I tried to update to `0.27.0` my build failed because of the following error: 

```
Error: Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".
```
also in the dev server I get the following error:

![Screenshot 2022-06-09 at 11 56 46](https://user-images.githubusercontent.com/21695702/172820650-ffcb4fc9-2e0e-4f7e-8407-ef26866694ba.png)

In my project I'm using custom ids for all instances of `@docusaurus/plugin-content-docs`.

When I remove the custom plugin id for one instance everything works as expected. In my case it would be great if I could still continue to use custom ids for all my plugin instances.

**Comment by weareoutman** [comment]
Are u using versioned docs? if not, try to use 0.26.x. This issue is probably a regression introduced in v0.27.0 when implementing versioned docs. We will try to fix it later.

**Comment by noobinthisgame** [comment]
Thanks @weareoutman :) I'm going to stay on 26.1 until then.

**Comment by weareoutman** [comment]
Thanks for reporting, can you share your config about how you're using custom ids?

**Comment by noobinthisgame** [comment]
Essentially I have this in my config which causes the error: 

```
const config = {
  ...
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'customPlugin1',
        path: './docs/customPlugin1',
        routeBasePath: 'customPlugin1',
        showLastUpdateAuthor: false,
        showLastUpdateTime: false,
        include: ['**/*.md', '**/*.mdx'],
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'customPlugin2',
        path: './docs/customPlugin2',
        routeBasePath: 'customPlugin2',
        showLastUpdateAuthor: false,
        showLastUpdateTime: false,
        include: ['**/*.md', '**/*.mdx'],
      },
    ],
  ],
}
```

Seems like this piece of code that got introduced causes the problem:
https://github.com/easyops-cn/docusaurus-search-local/blob/master/docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx#L51-L54

`useActiveVersion` tries to find a plugin with a default id when no id is passed to it.

Workaround that works with `0.27.0` is to go like this: 

```
const config = {
  ...
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        path: './docs/customPlugin1',
        routeBasePath: 'customPlugin1',
        showLastUpdateAuthor: false,
        showLastUpdateTime: false,
        include: ['**/*.md', '**/*.mdx'],
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'customPlugin2',
        path: './docs/customPlugin2',
        routeBasePath: 'customPlugin2',
        showLastUpdateAuthor: false,
        showLastUpdateTime: false,
        include: ['**/*.md', '**/*.mdx'],
      },
    ],
  ],
}
```

But is not what I need as in other custom plugins I use the custom ids.

**Comment by Cyriuz** [comment]
I added a fix for this I think in #205, didn't feel worth it to fix in the old solution that is already not working.

**Comment by weareoutman** [comment]
This issue seems not to be fixed yet

**Comment by weareoutman** [comment]
This maybe fixed in v0.29.1 via #226 , try it if you're not using versioned docs at the same time (there maybe still issues with versioned docs).

Feel free to reopen it if the problem still exists. But we will track the issue of versioned docs in #224

**Comment by weareoutman** [comment]
There is still an issue when the first docs instance has an `id` other than default. I'll fix it soon.

**Comment by weareoutman** [comment]
Finally fixed in v0.29.2. However you should add a new option `docsPluginIdForPreferredVersion`:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/2338946/179664947-5db12548-a6af-443e-b9d5-36991569b137.png">

**Comment by ivishalgandhi** [comment]
I am running into the same error message 

`Error: Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".`

As a newbie to Docusaurus and react.js, please share the required configuration for `docusaurus.config.js` at present I am using 

```js
  themes: [
    // ... Your other themes.
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        // ... Your options.
        // `hashed` is recommended as long-term-cache of index file is possible.
        hashed: true,
        // For Docs using Chinese, The `language` is recommended to set to:
        // ```
        // language: ["en", "zh"],
        // ```
      },
    ],
  ],
```

**Comment by weareoutman** [comment]
@ivishalgandhi You should try the suggestion above: 

> Finally fixed in v0.29.2. However you should add a new option `docsPluginIdForPreferredVersion`:
> 
> <img alt="image" width="845" src="https://user-images.githubusercontent.com/2338946/179664947-5db12548-a6af-443e-b9d5-36991569b137.png">

**Comment by ivishalgandhi** [comment]
@weareoutman Thank you. I am not using plugins anywhere in the docusaurus.config.js. how and where should I use above configuration.

**Comment by weareoutman** [comment]
@ivishalgandhi Can you share your full `docusaurus.config.js`? You can remove sensitive data as you wish.

**Comment by ivishalgandhi** [comment]
@weareoutman 

```shell
✖ Server
  Compiled with some errors in 8.35s

[ERROR] Docusaurus server-side rendering could not render static page with path /404.html.
[ERROR] Docusaurus server-side rendering could not render static page with path /about.
[ERROR] Docusaurus server-side rendering could not render static page with path /archive.
[ERROR] Docusaurus server-side rendering could not render static page with path /docker-sbom.
[ERROR] Docusaurus server-side rendering could not render static page with path /local-home-lab.
[ERROR] Docusaurus server-side rendering could not render static page with path /markdown-page.
[ERROR] Docusaurus server-side rendering could not render static page with path /search.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/dnsmasq.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/docker.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/docker-desktop.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/lab.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/nginx.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/reverse-proxy.
[ERROR] Docusaurus server-side rendering could not render static page with path /tags/sbom.
[ERROR] Docusaurus server-side rendering could not render static page with path /.


Error: Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".
```

**Comment by weareoutman** [comment]
@ivishalgandhi ok, I have just reproduced it. It happens when docs disabled

**Comment by ivishalgandhi** [comment]
@weareoutman  yes . thank you

**Comment by weareoutman** [comment]
@ivishalgandhi Fixed in v0.30.1. P.S. you still need to set `indexDocs: false`

**Comment by weareoutman** [comment]
@ivishalgandhi I think you should set `blogRouteBasePath: "/"` according to your blog config

**Comment by ivishalgandhi** [comment]
@weareoutman  works fine

**Comment by aryzing** [comment]
Is this issue resolved? I just set up a clean install of docusaurus with `create-docusaurus@latest` and have a single plugin and no preset,

```js
  plugins: [
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "default", // had to set this to default (or remove it, which is equivalent), other values crashed the site
        path: "my-path",
        routeBasePath: "my-base-path",
        sidebarPath: require.resolve("./sidebars.js"),
      },
    ],
  ],
```

Using an `id` other than `default` shows an error in the built doc site,

> Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".

**Comment by weareoutman** [comment]
@aryzing Try this option:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2338946/211819937-028f28ea-a26a-42ef-8fba-48d316a42692.png">
