### ISSUE TITLE
怎么设置可以搜索时不分词，完全和搜索的词语100%匹配？

### ISSUE THREAD

**Issue by brianler** [easyops-cn/docusaurus-search-local#223]
你好，怎么设置可以搜索时不分词，完全和搜索的词语100%匹配？

**Comment by weareoutman** [comment]
你指的是搜索时只做类似 `content.includes(keyword)`（`content` 是整篇文章的内容）的工作？目前不提供这个能力，没有想到什么场景需要这样做。

或者指的是 content 做分词，但 keyword 需要完整匹配，不对 keyword 分词或模糊匹配或词形变化等处理？这个目前不支持，但理论上可以去做，类似搜索引擎使用半角双引号 `"keyword"` 的效果。

P.S. 建议下次使用英语来提 issue，这样回答你的问题的人群范围可以扩大很多。

**Comment by brianler** [comment]
> 你指的是搜索时只做类似 `content.includes(keyword)`（`content` 是整篇文章的内容）的工作？目前不提供这个能力，没有想到什么场景需要这样做。
> 
> 或者指的是 content 做分词，但 keyword 需要完整匹配，不对 keyword 分词或模糊匹配或词形变化等处理？这个目前不支持，但理论上可以去做，类似搜索引擎使用半角双引号 `"keyword"` 的效果。
> 
> P.S. 建议下次使用英语来提 issue，这样回答你的问题的人群范围可以扩大很多。

是的，应该是content分词，keyword不分词，类似我们用adobe pdf和word搜索关键词那样。

**Comment by brianler** [comment]
另外，我想确认一下。搜索时，点击弹出框里面的结果，跳转到相应页面关键字会高亮。但是在显示全部结果那里，点击跳转页面不会显示高亮关键字。这是什么原因

**Comment by weareoutman** [comment]
> 另外，我想确认一下。搜索时，点击弹出框里面的结果，跳转到相应页面关键字会高亮。但是在显示全部结果那里，点击跳转页面不会显示高亮关键字。这是什么原因

那可能是漏了实现...

**Comment by brianler** [comment]
了解
