### ISSUE TITLE
search no longer working > 26.1

### ISSUE THREAD

**Issue by andrewgbell** [easyops-cn/docusaurus-search-local#224]
Hi,

When we upgrade from 26.1 to any of the later versions, our search never returns any results (continually swirls and never errors).

I presume this is to do with the versioned search, which is something we definitely would like, but the straight upgrade seems to break our search.  We use docs only and have 3 areas similar to those below:

      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        hashed: true,
        docsRouteBasePath: ["docs1","docs2","docs3"],
        docsDir: ["docs1","docs2","docs3"],

To enable versioning or is there a breaking change?  I can't see anything in the documentation about why upgrading beyond 26.1 would cause the issue.

**Comment by weareoutman** [comment]
Are you using versioned docs at the same time besides using multiple docs dir?

**Comment by weareoutman** [comment]
It will help more if you can share your relevant config options of  `@docusaurus/plugin-content-docs`, or `docs` in `@docusaurus/preset-classic`.

**Comment by andrewgbell** [comment]
yes, using versioned docs for two of our docs folders and one isn't.  Hopefully, the below helps:

`plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'main',
        path: 'main',
        routeBasePath: 'main',
        sidebarPath: require.resolve('./sidebars.js'),
        includeCurrentVersion: true,
        editUrl: 'https://github.com/blah/',
        versions: {
          '2.8': {
            banner: 'none',
            path: '2.8',
          },
          '2.9': {
            banner: 'none',
            path: '2.9',
          },
        }
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'secondary',
        path: 'secondary',
        routeBasePath: 'secondary',
        sidebarPath: require.resolve('./sidebars.js'),
        includeCurrentVersion: true,
        editUrl: 'https://github.com/blah2/',
        versions: {
          '7.3': {
            banner: 'none',
            path: '7.3',
          },
          '7.4': {
            banner: 'none',
            path: '7.4'
          }
        }
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'support',
        path: 'support',
        routeBasePath: 'support',
        sidebarPath: require.resolve('./sidebars.js')
      },
    ],
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        hashed: true,
        docsRouteBasePath: ["main","secondary","support"],
        docsDir: ["main","secondary","support"],
      },`

**Comment by weareoutman** [comment]
This may be related #211

**Comment by andrewgbell** [comment]
Ah ok thanks, looks similar.

**Comment by weareoutman** [comment]
I think this is also fixed by #228
