### ISSUE TITLE
UI issues on the phone screen

### ISSUE THREAD

**Issue by ZACHSTRIVES** [easyops-cn/docusaurus-search-local#230]
Hi, The following small problem was found on the phone screen：

**1: The "X" clear button in the input box remains after the answer is searched and clicked to jump.**
![611658277366_ pic](https://user-images.githubusercontent.com/54759064/179871068-22acc176-b350-4694-bed1-2e963604de3a.jpg)

**2: When you click search, the page will automatically zoom in and focus, this user experience is very good! But when you finish the search and click on the answer to jump, this magnifying and focusing effect will still be maintained on the page after the jump.**

![631658277551_ pic](https://user-images.githubusercontent.com/54759064/179871486-c70e5be5-d242-4832-a387-b79be50d6bde.jpg)

Thanks！

**Comment by weareoutman** [comment]
Thanks for reporting, the first issue is a bug, we'll working on it later.

For the second one, we probably can't do anything, the zooming effect is applied by Safari. But you can try overriding the [viewport meta](https://stackoverflow.com/a/46254706) yourself by configuring your docusaurus.

**Comment by ZACHSTRIVES** [comment]
Thanks！
