### ISSUE TITLE
Multiple instances of docs/blog folders

### ISSUE THREAD

**Issue by btey** [easyops-cn/docusaurus-search-local#24]
It would be very nice if the variables:
- docsRouteBasePath
- blogRouteBasePath
- docsDir
- blogDir

... they were arrays that allow declaring more than one directory when you have multiple instances of "docs" or "blog". Or if it is currently possible to declare more than one "docs/blog", include in the documentation how to do it.

Thank you very much!!

**Comment by weareoutman** [comment]
Hi, it is supported in v0.12.0, try it out.
