### ISSUE TITLE
[feature request] `jieba.loadDict` support (支持词典扩展)

### ISSUE THREAD

**Issue by Airkro** [easyops-cn/docusaurus-search-local#246]
The effect of Chinese word segmentation is not good enough. I hope to expand the vocabulary by myself, so corresponding options are required.

---

目前中文分词效果不理想，希望能够自行扩充词库，因此需要相应选项。

```cjs
const { cut } = require('@node-rs/jieba');

cut('微信小程序');

// [ '微', '信', '小', '程序' ]
```

```cjs
const { cut, loadDict } = require('@node-rs/jieba');

const dist = `
微信 100
小程序 100
`;

const userdict = Buffer.from(dist);

loadDict(userdict);

cut('微信小程序');

// [ '微信', '小程序' ]
```

**Comment by weareoutman** [comment]
That sounds reasonable. We can let users opt-in to extend the dict, E.g.: `zhUserDict` and `zhUserDictPath`, which the latter one allows user to put the dict in a separate file. PRs are welcome, :)
