### ISSUE TITLE
Display search on another language

### ISSUE THREAD

**Issue by guidopontet** [easyops-cn/docusaurus-search-local#251]
¿There is a way to display search interface on another language? For example, placeholder on spanish:

![image](https://user-images.githubusercontent.com/27219728/184543680-367b580e-c2fb-4e96-98ab-b38dc21e1230.png)

**Comment by weareoutman** [comment]
Yes, you can follow [the document on our project homepage](https://github.com/easyops-cn/docusaurus-search-local#i18n), to translate it on your own website project:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/2338946/184561632-9efa19e9-8963-40b4-8e88-79b0c29a2077.png">


Or any PRs which contributes to our built-in translations are welcome too.
