### ISSUE TITLE
It would be convenient to add a line to the translations

### ISSUE THREAD

**Issue by phoenixweiss** [easyops-cn/docusaurus-search-local#259]
https://github.com/easyops-cn/docusaurus-search-local/blob/a901c40139e75f66974d9d3e452c20ed736bcda0/docusaurus-search-local/src/client/theme/SearchBar/EmptyTemplate.ts#L14

I propose to do something like this:

```js
translate({
    id: "theme.SearchBar.buildWarning",
    message: "⚠️ The search index is only available when you run docusaurus build!",
})
```

**Comment by weareoutman** [comment]
This message only shows in development mode, end users will never see it. So I think there is no need to translate this message.
