### ISSUE TITLE
left / right search bar position

### ISSUE THREAD

**Issue by noraj** [easyops-cn/docusaurus-search-local#263]
When the search bar is on the left of the navbar, the results are cropped:

```js
        {
          type: 'search',
          position: 'left',
        },
```

![image](https://user-images.githubusercontent.com/16578570/188286271-20b1eff8-39ae-46e4-a67c-7c81496eec83.png)

while it's ok when the search bar is on the right of the navbar:

```js
        {
          type: 'search',
          position: 'right',
        },
```

![image](https://user-images.githubusercontent.com/16578570/188286422-51cee2a3-13e4-41ba-ad11-4b64ec680b00.png)

So I guess the style should depend on the side where the search bar is. If the side can't be retrieved directly from `docusaurus.config.js` then having a `position` option in the plugin config to alight with the search bar side would be required.

**Comment by weareoutman** [comment]
Supported in v0.32.0, will autodetect the search bar position, but also allow users to configure manually by `searchBarPosition: "left"`.
