### ISSUE TITLE
When navigating from search results page, the highlighting is not retained.

### ISSUE THREAD

**Issue by srbhaski** [easyops-cn/docusaurus-search-local#266]
The search results page shows the highlighting
![image](https://user-images.githubusercontent.com/54976344/188796826-0f76efee-3911-45c3-8309-1d44d6cc1f0e.png)

but when we click on the search result and navigate to the specific page, the highlighting is not retained.  The url does not have the text **_highlight=test** because of which the highlighting is not present.  Could you please address this soon.
![image](https://user-images.githubusercontent.com/54976344/188797054-6d7aba8f-aa1e-4050-9c6b-ecb372f32265.png)

**Comment by brianler** [comment]
@weareoutman @srbhaski 
i just solved the problem.
see: https://github.com/easyops-cn/docusaurus-search-local/pull/283
