### ISSUE TITLE
Cannot mix different versions of joi schemas

### ISSUE THREAD

**Issue by Chasen-Zhang** [easyops-cn/docusaurus-search-local#270]
"@docusaurus/core": "2.0.0-beta.14",
"@docusaurus/plugin-google-gtag": "2.0.0-beta.14",
"@docusaurus/preset-classic": "2.0.0-beta.14",
"@easyops-cn/docusaurus-search-local": "^0.32.0",

Which tag should be used for version 2.0.0-beta.14 ?

**Comment by chitralverma** [comment]
ensure that you are no longer having `@cmfcmf/docusaurus-search-local` in the package.json

**Comment by weareoutman** [comment]
According to our [trouble shooting](https://github.com/easyops-cn/docusaurus-search-local#trouble-shooting) doc:

> Try using @easyops-cn/docusaurus-search-local < v0.25.0 with Docusaurus < v2.0.0-beta.18

However, I will suggest you to use the latest version of docusaurus and our plugin, which fixed a lot of problems, as well as with a lot of features.
