### ISSUE TITLE
MultiDocs instances (Versioning not working) 

### ISSUE THREAD

**Issue by caradragos95** [easyops-cn/docusaurus-search-local#271]
I want to make the plugin search only in the selected version from the versioning dropdown, right now it doubles all the results as I have two versions of the docs:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/104777859/192703635-02fb1ca7-a6e0-4773-bc24-c44739d1c340.png">

![image](https://user-images.githubusercontent.com/104777859/192703207-7a314f5a-f3f4-4e73-b836-b196d19ab659.png)

**Comment by weareoutman** [comment]
According to the error message, I doubt you're using an old version of our plugin which doesn't support multi versions. Try to upgrade it to the latest one (currently v0.32.1).

**Comment by weareoutman** [comment]
I will close it now, feel free to reopen it if the issue still exists.
