### ISSUE TITLE
Control which search results are shown via a predicate function

### ISSUE THREAD

**Issue by hs-saunved** [easyops-cn/docusaurus-search-local#275]
We have a use case where we want to show only specific search results for specific pages.
E.g. If the user is in the `/android` path, only results from this path should be shown to them.

Is it possible to achieve this currently? Is there a hook that we can use to filter the search results ourselves?
If not, would it be possible to create a mode that allows for a narrower search within the base path only?

Thanks!

Edit: I believe this issue is also related https://github.com/easyops-cn/docusaurus-search-local/issues/99

**Comment by weareoutman** [comment]
I think it's possible, just like those using multi-versions, we can generate multiple indexes for each of your doc directories.

I think we can provide an option to allow developers to do it by base path or specific directories.

**Comment by weareoutman** [comment]
By the way, in your scenario, do you wish to search all docs when you're on the homepage `/`? This may change how we implement it.

**Comment by weareoutman** [comment]
> By the way, in your scenario, do you wish to search all docs when you're in the homepage `/`? This may change how we implement it.

If the answer is yes, we can't put the docs into different indexes, because if we do that, the search will not work in `/`. Instead, with a single index file, and we can only filter the search results manually.

**Comment by hs-saunved** [comment]
Thanks for the quick response @weareoutman!

For our use case, we are okay with not having a search bar on the home page. The home page is a list/index of all of our SDKs and fairly easy to navigate. If required, we can always create a custom search bar on the homepage itself.

Separate indexes per base path would be fantastic. It will cause less confusion for users when searching, since they expect to get results from the existing context itself.

**Comment by hs-saunved** [comment]
@weareoutman 
Can we do something like this?
```js
      [
        require.resolve("@easyops-cn/docusaurus-search-local"),
        {
          // ... other options
          // creates separate indexes for these base paths
          createIndexesByPaths: ["android", "ios", "web", ...]
        }
      ]
```

AND/OR

```js
      [
        require.resolve("@easyops-cn/docusaurus-search-local"),
        {
          // ... other options
          // deep: false won't pick up any nested folders, while deep:true picks up all nested folders
          createIndexesByPaths: [{path: "android", deep: false}, {path: "android/legacy", deep: true}] 
        }
      ]
```

I think both mechanisms would be useful. I was looking at the source code to see how this could be implemented. I am slightly confused about where the index is getting generated as well as how the autocomplete component works. Thanks!

**Comment by weareoutman** [comment]
There is [a WIP branch](https://github.com/easyops-cn/docusaurus-search-local/tree/steve/search-context), I couldn't finish it yet. I will continue this work this weekend if I got time.

**Comment by hs-saunved** [comment]
Checked the commits. Do you think it's a good idea to provide the user an option to give explicit groups of base paths like in my comment example above?

**Comment by weareoutman** [comment]
Yes, I think an option with explicit paths would be better, it's also easier to implement.

**Comment by weareoutman** [comment]
@hs-saunved Try v0.33.0

**Comment by hs-saunved** [comment]
Hi @weareoutman 
The functionality is working as expected. However, there are two small things that need to be fixed/checked:

### Issue 1
- Let's say you are in the `android` context
- You switch to the `ios` context by clicking on an internal link
- The search context is still set to `android`, and the results show up from `android`
- This is only fixed if you refresh the page
- Ideally the context should be set whenever the user switches base paths imo

### Issue 2
- For pages which are not specified in the `searchContextByPaths` key - I believe the search bar should stay hidden. Same for other pages where the base path has not been explicitly specified
- E.g. for the home page, the search bar is visible and is doing a global search even if I haven't explicitly added it

---

Please let me know if you'd like me to create separate issues for this or if this is okay. Thank you!

**Comment by weareoutman** [comment]
Issue 1 should have already being handled, needs investigation.

For issue 2, I think we'd better to provide a new option, currently all pages which are not specified, will be considered as a with a search context of ROOT.

**Comment by weareoutman** [comment]
@hs-saunved Try v.0.33.1 with a new option: `hideSearchBarWithNoSearchContext: true`

**Comment by hs-saunved** [comment]
@weareoutman It is working as expected! I will test this out over the week and report any potential issues or optimizations. Thank you very much!
