### ISSUE TITLE
cannot update to latest version

### ISSUE THREAD

**Issue by caradragos95** [easyops-cn/docusaurus-search-local#278]
I tried to update to the latest version, but it appears that it is still on 0.26.1
![image](https://user-images.githubusercontent.com/104777859/195270429-1bc814eb-fef4-4b82-989b-dc594c026a12.png)

**Comment by weareoutman** [comment]
`npm update` will update the dependency according to the semver you specified in package.json. So if you have `@easyops-cn/docusaurus-search-local": "^0.26.1"`, you will not get the actual latest version by `npm update`.

Instead, you should first manually update your package.json with the latest version (currently its `^0.33.2`), then run `npm install`.
