### ISSUE TITLE
”yarn add @easyops-cn/docusaurus-search-local “ 命令 在 node v16.15.1中拉取错误

### ISSUE THREAD

**Issue by dongjycode** [easyops-cn/docusaurus-search-local#297]
`error An unexpected error occurred: "https://registry.npmmirror.com/mark.js/-/mark.js-8.11.1.tgz: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dongjunyang/private/docusaurus-demo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/91414395/200315715-abd00eae-7369-4626-a62d-72179b1a59e0.png">

**Comment by dongjycode** [comment]
当使用nvm切换node版本为v18.4.0时，即node 18版本可以正常拉取

**Comment by weareoutman** [comment]
You're using a mirror of npm, I suppose it's a issue of that npm. Try using official npm or other mirrors.
