### ISSUE TITLE
Keyboard shortcut depends on keyboard layout

### ISSUE THREAD

**Issue by stropitek** [easyops-cn/docusaurus-search-local#298]
The shortcut for search is Cmd+K / Ctrl+K

However when using an exotic keyboard layout (I myself am using dvorak), it does not work when using the letter `K` on this layout.

I think this might be because the shortcut is handled based on the keyboard event's [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) and not [`key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).

**Comment by weareoutman** [comment]
Hi, thanks for reporting, fixed in 0.33.6
