### ISSUE TITLE
Support search within React components using MDX

### ISSUE THREAD

**Issue by tobiasbueschel** [easyops-cn/docusaurus-search-local#307]
Hi there,

Great plugin for Docusaurus - really appreciate all your efforts with it.

Have you looked into supporting text search within React components that are part of MDX files? In our current application we have a few custom card components that we're rendering in MDX on various pages. Unfortunately, none of the cards is searchable.

Thanks

**Comment by weareoutman** [comment]
Hi, I think it's working with MDX. Try our [demo site](https://easyops-cn.github.io/docusaurus-search-local/docs/next/intro) and search "blue". It's [a mdx file](https://github.com/easyops-cn/docusaurus-search-local/blob/master/website/docs/tutorial-basics/markdown-features.mdx).

Our search index is based on the static html files generated by docusaurus. Make sure your content is static in production.

**Comment by tobiasbueschel** [comment]
Thanks for the reply @weareoutman - I've checked the example and noticed that the Component in the MDX file passes down the text in the children prop.

For my use case, the text is passed down in these props:

```jsx
<UserProfileCard
  name="John Doe"
  location="Singapore"
  role="Site Reliability Engineer"
/>
```

Hence, the text will only render when the component interprets the e.g., name prop and is not stated within the MDX file itself. My guess is that [docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local) only searches for the text within the MDX file and doesn't evaluate the text of a prop within a component.

**Comment by weareoutman** [comment]
Under the hood, this plugin create the search index by the generated static html files by Docusaurus.

As mentioned above:

> Make sure your content is static in production (can be server-side-rendered).

E.g., if your content is displayed relied on remote requests or similar logic that prevent the page to show its content at initial, we can't index that.

**Comment by tobiasbueschel** [comment]
I found the culprit, at the beginning of the component tree another person added [BrowserOnly](https://docusaurus.io/docs/docusaurus-core#browseronly) as a wrapper, which caused the browser to only render the component after the React app has hydrated.

Therefore, [docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local) wasn't able to find it.

I'll go ahead and close this issue :)

Thanks
