### ISSUE TITLE
Cannot mix different versions of joi schemas

### ISSUE THREAD

**Issue by rafaelrdealmeida** [easyops-cn/docusaurus-search-local#31]
I upgraded docusaurus alpha.66 to alpha.68 and I had a version conflict with joi. @ hapi/joi is in version 17.1.1 and joi is in version 17.3.0. wouldn't it be worth leaving joi@17.3.0 as a dependency instead of @ hapi/joi@17.1.1?

**Comment by weareoutman** [comment]
Um, yes, we should upgrade the joi dependency now. This plugin is trying to keep `joi` the same version as  Docusaurus, which alhpa.66 depends on `@hapi/joi` and now alpha.68 depends on `joi`.

**Comment by weareoutman** [comment]
@rafaelrdealmeida try v0.14.0 which supports docusaurus v2.0.0-alpha.68 ☕️

**Comment by rafaelrdealmeida** [comment]
Hello it worked perfectly, thanks!

**Comment by eric-hc** [comment]
I'm seeing this issue again with these versions 😟 

```javascript
"@docusaurus/core": "^2.0.0-alpha.71",
 "@docusaurus/preset-classic": "^2.0.0-alpha.71",
 "@easyops-cn/docusaurus-search-local": "^0.15.0",
```

**Comment by weareoutman** [comment]
@eric-hc oops, there is currently a workaround to fix this error, run `npx yarn-deduplicate yarn.lock` if you're using yarn, or run `npm dedupe` if you're using npm.

I will try to figure out a better solution to solve this issue later this week.

**Comment by weareoutman** [comment]
Let's wait Docusaurus alpha 73 ☕️ . FYI https://github.com/facebook/docusaurus/issues/4456#issuecomment-802155410

**Comment by weareoutman** [comment]
Try v0.16.0 with Docusaurus alpha 73.

**Comment by ltribolet** [comment]
I think this happening again with beta 16.

**Comment by jason71708** [comment]
For someone who encounters this issue. Just delete your `.lock` file and install dependency again.

**Comment by BorjanKalinoski** [comment]
Removing `package-lock.json`, `node_modules`, and removing the `^` from the version, i.e. from `^17.6.0` to `17.6.0` fixed the issue.

Having a monorepo, different services installed different versions of joi, which caused the issue

**Comment by rosibaj** [comment]
This is happening again i believe with the new Docusaurus beta.
```
[INFO] Docusaurus version: 3.0.0-beta.0
Node version: v18.0.0
```
