### ISSUE TITLE
 zh search  input ten more word the page will  crash

### ISSUE THREAD

**Issue by liuxing95** [easyops-cn/docusaurus-search-local#312]
https://doris.apache.org/zh-CN/docs/dev/summary/basic-summary/ this url use  docusaurus-search-local

<img width="908" alt="image" src="https://user-images.githubusercontent.com/27283200/211539539-2e361d56-d00e-4504-b2ab-7a3830949b36.png">
it will always loading and i can't control this page

**Comment by liuxing95** [comment]
the chinese search  when user input ten more words it will always loading

**Comment by weareoutman** [comment]
There seems to be a performance issue when searching with a large number of Chinese words with a huge search index of docs in Chinese, :(. I'll look into it later.

**Comment by tcy1999** [comment]
Hello, same issue here. Any ideas how to fix this problem?

**Comment by zjy365** [comment]
@weareoutman 
This is a serious vulnerability that hopefully will be addressed.
Entering a relatively long search text into the search box will cause the page to crash directly.
I think it has something to do with this call.

<img width="734" alt="image" src="https://github.com/easyops-cn/docusaurus-search-local/assets/72259332/e8f7dbed-1794-498d-bfaf-4791a6d54c08">

**Comment by beckjin** [comment]
+1

**Comment by weareoutman** [comment]
Fixed in v0.45.0

**Comment by weareoutman** [comment]
Also note that we use Web Worker to do the search now, since [v0.46.1](https://github.com/easyops-cn/docusaurus-search-local/releases), so it will not block the main UI.
