### ISSUE TITLE
Question: is it possible to ignore a folder?

### ISSUE THREAD

**Issue by Nikoms** [easyops-cn/docusaurus-search-local#324]
Hello,

I'm working in a mono repo where each package has its own `README.md`. For simplicity, my `docsDir`is basically the root of all packages.

The problem is that is also browse in the `node_modules` folder so I need to delete the folder before building the website. I tried to add the node_modules in `ignoreFiles`, but it doesn't take that parameter into consideration in the `hash` process.

Thank you for your help 🙏

**Comment by skosysparency** [comment]
How did you configure this? eg this regex works for my 'db' folder an subfolders:
`ignoreFiles: [/docs\/db\/.*/]`

**Comment by Nikoms** [comment]
Hey, I'm sorry there was a problem with symlink. It's working like a charm.

Thank you and sorry
