### ISSUE TITLE
`blogDir` allows `[]`

### ISSUE THREAD

**Issue by rainecheck** [easyops-cn/docusaurus-search-local#342]
While removing the blog from a site, I noticed that there was some inconsistent behaviour with the declaration of `blogDir`:

| Syntax            | Returns | Result                                                            |
| ----------------- | ------- | ----------------------------------------------------------------- |
| `blogDir: ""`     | Error   | [ERROR] ValidationError: "blogDir" is not allowed to be empty     |
| `blogDir: null`   | Error   | [ERROR] ValidationError: "blogDir" must be one of [string, array] |
| `// blogDir: ""`  | Warning | Warn: `blogDir` doesn't exist: "{snip}/blog".                     |
| `blogDir: [""]`   | Error   | [ERROR] ValidationError: "blogDir[0]" is not allowed to be empty  |
| `blogDir: [null]` | Error   | [ERROR] ValidationError: "blogDir[0]" must be a string            |
| `blogDir: []`     | Success | No issues, works fine.                                            |

Allowing an empty array but not allowing an empty string or a null string seems like it's not intended.

The use case for me here is to declare `indexBlog: false`, but thought I'd raise this an a minor issue.

**Comment by doraeric** [comment]
Took me a while to find the cause of the message
```
Warn: `blogDir` doesn't exist: "..."
```

Google search doesn't index this page somehow.

The solution is given above: set `indexBlog: false`. This option comes from the [theme options](https://github.com/easyops-cn/docusaurus-search-local?tab=readme-ov-file#theme-options)

I think it's better to show it comes from this package, so developers can find relevant config.

**Comment by weareoutman** [comment]
Yes, you should set `indexBlog: false` to disable indexing for blog, only set `blogDir` when you have blog placed in other than the default one `"blog"`
