### ISSUE TITLE
Should search find documents based on front-matter keywords?

### ISSUE THREAD

**Issue by hatton** [easyops-cn/docusaurus-search-local#344]
My [pages ](https://docs.bloomlibrary.org/windows-controlled-folder-access/)have, for example:

```
---
title: Unblocking Bloom from Windows Controlled Folder Access
sidebar_position: 5
slug: /windows-controlled-folder-access
keywords: [troubleshooting, Defender, controlled, folder]
---
```

I find that search will find terms in the `title`, but not the `keywords`. For example, I would expect that if I search for "troubleshooting", this document would be listed. Is there something I can do to start indexing on `keywords`?

**Comment by alexchantastic** [comment]
➕ On this feature request!

For now, I've just added some hidden content on my page that includes the keyword. Definitely not ideal though.

**Comment by lyleaigbedion** [comment]
Looking for this behaviour as well. 

This is available with https://github.com/praveenn77/docusaurus-lunr-search which I switched from due it's lack of style customization

**Comment by weareoutman** [comment]
It is possible to make search based on keywords, if they are appeared in the generated HTML.

such as:

```html
<meta name="keywords" content="...">
```

Currently it is not supported, PRs welcome. If no one is interested in, I'll do it once I got time.

**Comment by weareoutman** [comment]
Searching based on keywords (and description) from meta tags (front matter in markdown) is supported via 0.41.0
