### ISSUE TITLE
Support for Docusaurus 3.0

### ISSUE THREAD

**Issue by IanVS** [easyops-cn/docusaurus-search-local#345]
Docusaurus released an alpha of 3.0 last month which includes support for react 18.  I tried to upgrade, but I see that I get peer dependency warnings for this plugin.  

Do you plan to release an update which will support docusuarus 3?

**Comment by litttley** [comment]
the same issues

**Comment by csantos-nydig** [comment]
FWIW, Docusaurus 3 is in RC https://github.com/facebook/docusaurus/releases/tag/v3.0.0-rc.0

**Comment by limansky** [comment]
Docusaurus 3.0.0 is released https://github.com/facebook/docusaurus/releases/tag/v3.0.0

**Comment by weareoutman** [comment]
Just released v0.37.1 which supports Docusaurus v3
