### ISSUE TITLE
Enable prebuild indexing

### ISSUE THREAD

**Issue by albert-schilling** [easyops-cn/docusaurus-search-local#347]
Is it conceivable to build the search index independently of the build step? E.g. only based on the markdown files in the docs folder?

We have the issue, that we are using client-side authentication in our Docusaurus build and thus, had to use a work around (as described here: https://github.com/easyops-cn/docusaurus-search-local/issues/210#issuecomment-1359700323 ) to solve this.

It would be great if you could choose between using the build folder or let's say the original docs folder to create the search index.

**Comment by weareoutman** [comment]
Related issue #210

**Comment by weareoutman** [comment]
Currently no, under the hood, we parse the generated html files to build the search index (just like a server side search engine). We can't build the index by parsing markdown files because they may contain information that is not available until runtime, such as React components in mdx.

**Comment by albert-schilling** [comment]
> Currently no, under the hood, we parse the generated html files to build the search index (just like a server side search engine). We can't build the index by parsing markdown files because they may contain information that is not available until runtime, such as React components in mdx.

That makes total sense. Thanks for the explanation.
