### ISSUE TITLE
Docusaurus React Root onRecoverableError: Error: Minified React error #418 and #423

### ISSUE THREAD

**Issue by namnguyenthanhwork** [easyops-cn/docusaurus-search-local#364]
## Description
Every website using `docusaurus v3` and `docusaurus-search-local` has an error `Minified React error #418 and #423`

When `docusaurus v3` release, it causes the `docusaurus-search-local` appear an error.
An issue appear only production or run command:

```
npm run build
npm run serve
```

If you using `docusaurus v2` and `docusaurus-search-local <= v0.35.0` there will be no such error.

How to fix it ?

<img width="645" alt="image" src="https://github.com/easyops-cn/docusaurus-search-local/assets/78526193/5e39b24e-8cfa-496e-8b82-42c69b83a50f">

**Comment by weareoutman** [comment]
I can't reproduce it, can you provide a link or repro steps?

**Comment by pranabdas** [comment]
This seems to appear only in the production. Currently, your demo website shows it <https://easyops-cn.github.io/docusaurus-search-local/>. Alternatively:
```console
npm run build
npm run serve
```

**Comment by namnguyenthanhwork** [comment]
@weareoutman I updated description

**Comment by weareoutman** [comment]
I see, it does show these errors in console, but the page and search bar works as normal?

**Comment by namnguyenthanhwork** [comment]
@weareoutman As I see, page and search bar works as normal, just show these errors in console.
