### ISSUE TITLE
Use Tesseract.js to extract text from images and include in search-index.json

### ISSUE THREAD

**Issue by tobiasbueschel** [easyops-cn/docusaurus-search-local#379]
Hi @easyops-cn Team,

Great project 👏 I'd like to share the following feature idea:

I often use images that contain a lot of text within Docusaurus and it would be amazing if this text would also be searchable through this plugin. What do you think about adding an optional OCR step to extract any text found in the images of the docusaurus repository and including it in the `search-index.json`?

One could achieve this using: [tesseract.js](https://github.com/naptha/tesseract.js) for example.
![OCR](https://github.com/naptha/tesseract.js/raw/master/docs/images/demo.gif)

**Comment by weareoutman** [comment]
I think it would be better to make an independent plugin which does the OCR job. Let it collect images in your articles, and add some hidden text into the output of HTML. Then the search will work as you expected.

**Comment by weareoutman** [comment]
Gonna close it, feel free to reopen it if you have other thoughts.
