### ISSUE TITLE
Multiple versioned Documents

### ISSUE THREAD

**Issue by AkshayRGhatge** [easyops-cn/docusaurus-search-local#381]
When dealing with multiple versioned documents on the site
1. Is there a way to include the version number in the search results?
2. When searching for an item, can the search results be limited to the items from the version which they have selected in the dropdown rather than displaying results from all versions.
for instance: looking for **Introduction** in this case it will display all the versions that contains **Introduction**

![multiple_result](https://github.com/easyops-cn/docusaurus-search-local/assets/96392298/6df5745a-effc-40b4-8b44-6d4c7227c5c8)

**Comment by weareoutman** [comment]
It is supported actually, even though there is a problem that requires refresh after switch versions, see #380 . But there shouldn't be mixed search results.

We need more information, such as `docusaurus.config.js` and related package versions.

**Comment by AkshayRGhatge** [comment]
**Update**: After updating the version for the easyops-cn with the latest version it is working fine but yea refresh is an issue after versions is swich.

> It is supported actually, even though there is a problem that requires refresh after switch versions, see #380 . But there shouldn't be mixed search results.
> 
> We need more information, such as `docusaurus.config.js` and related package versions.

**Comment by weareoutman** [comment]
OK, let's track it in #380
