### ISSUE TITLE
Is it possible to replace folders names (from the search context) to custom titles in dropdown options at the search page?

### ISSUE THREAD

**Issue by Elvehnn** [easyops-cn/docusaurus-search-local#382]
![image_2023-12-14_13-48-41](https://github.com/easyops-cn/docusaurus-search-local/assets/70837634/bf5ef881-eea9-4a25-9f52-219026d3b2cc)

docusaurus.config: 

  themes: [
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      /** @type {import("@easyops-cn/docusaurus-search-local").PluginOptions} */
      {
        language: ["en"],
        hashed: true,
        indexDocs: true,
        indexPages: true,
        indexBlog: false,
        docsRouteBasePath: "/",
        searchContextByPaths: ["user-guide", "developer-guide", "admin-guide"],
        hideSearchBarWithNoSearchContext: true,
      },
    ],
  ],

package.json
 "dependencies": {
    "@docusaurus/core": "3.0.1",
    "@docusaurus/preset-classic": "3.0.1",
    "@easyops-cn/docusaurus-search-local": "^0.38.1",

**Comment by weareoutman** [comment]
@Elvehnn Try 0.39.0 which supports `searchContextByPaths: [{ label: "Community", path: "community" }]`

<img width="419" alt="image" src="https://github.com/easyops-cn/docusaurus-search-local/assets/2338946/d88c8787-3b5f-4cee-b917-0ca117a9002f">

**Comment by Elvehnn** [comment]
Great! Thanx a lot!

**Comment by Elvehnn** [comment]
[weareoutman](https://github.com/weareoutman) and it would be great to be able to  use these labels with i18n for the multi-language apps.

**Comment by weareoutman** [comment]
Try [v0.40.0](https://github.com/easyops-cn/docusaurus-search-local/releases/tag/v0.40.0):

<img width="346" alt="image" src="https://github.com/easyops-cn/docusaurus-search-local/assets/2338946/061c476b-672f-4c63-8c85-c32ef3ea558f">
