### ISSUE TITLE
Local search with noIndex: true [feature request], was: No search results on local build

### ISSUE THREAD

**Issue by techbridgedev** [easyops-cn/docusaurus-search-local#385]
I installed the plugin per the instructions.

I do not have a blog directory on my site.

My config looks like this:

```themes: [
      [
        require.resolve("@easyops-cn/docusaurus-search-local"),
        ({
          hashed: true,
          highlightSearchTermsOnTargetPage: true,
          explicitSearchResultPath: true,
          indexBlog: false,
          indexPages: true
        })
      ]
    ],
```

Then I ran the build & started the server with `npm run serve` to serve from the build directory. Every search query returns empty ("no results").

I also ran the build with debug but saw no errors.

**Comment by techbridgedev** [comment]
The cause was the `noIndex` option in my config. The site is not for public consumption so I was discouraging search engines from crawling the site. So I'm turning this into a feature request: can we have an option to use `noIndex: true` but also have internal search work?

**Comment by weareoutman** [comment]
V0.38.0 introduced the feature: ignore unlisted context (the `noIndex` option has the similar effect).  Your can try previous versions to see it it works for you.

Maybe we can add an option to force enable local search even if `noIndex` is set.

**Comment by techbridgedev** [comment]
> Maybe we can add an option to force enable local search even if noIndex is set.

Please do!
