### ISSUE TITLE
Search page gives no results

### ISSUE THREAD

**Issue by canuto** [easyops-cn/docusaurus-search-local#389]
Thank you for making this available for docusaurus 3 users!

I noticed on my site https://codehooks.io that the separate search page gave no results (the one you can open when clicking "All results" in the search bar drop down).

The issue seems to be the same with your site.

https://github.com/easyops-cn/docusaurus-search-local/assets/30823/bdd72d00-6f60-41c6-8356-9d66b893314c

**Comment by chris48s** [comment]
This seems to be an issue introduced in the jump from 0.39.0 to 0.40.0

**Comment by CumpsD** [comment]
Confirmed, reverting back to 0.39.0 fixes this for me 👍🏻

**Comment by weareoutman** [comment]
Thanks for reporting, fixed in v0.40.1

**Comment by CumpsD** [comment]
Confirming it works again, thanks!
