### ISSUE TITLE
When I have multi product docs, how to filter the search result? 

### ISSUE THREAD

**Issue by heywalter** [easyops-cn/docusaurus-search-local#394]
We have 2 product documents in one document center. How can we filter the search results? For example, I only want to search for content in the first product document.

For more info about how to deploy multi-instance in one document center, see [Docs Multi-instance](https://docusaurus.io/docs/docs-multi-instance).

**Comment by weareoutman** [comment]
It's already supported, but require some config. See example in https://github.com/easyops-cn/docusaurus-search-local/blob/master/website-multi-docs/docusaurus.config.js#L156-L172

**Comment by heywalter** [comment]
Excuse me, is it something like this, we can specify the scope when searching or filtering the product?
![iShot_2024-01-12_10 34 52](https://github.com/easyops-cn/docusaurus-search-local/assets/92153708/99c36f05-1c7e-46b9-a630-5c29df33dd6a)

**Comment by weareoutman** [comment]
No, it will be filtered by current page URL. If you're visiting `/product/*`, the search scope will be limited to product pages. If you're visiting `/community/*`, the search scope will be limited to community pages.
