### ISSUE TITLE
Building index in the development environment

### ISSUE THREAD

**Issue by Lemon5269** [easyops-cn/docusaurus-search-local#401]
If I want to modify the existing search box style, after each adjustment, I need to execute `yarn build`, then `yarn serve`. The development experience is quite poor. How can I build the index in the development environment to implement the search function? Does anyone have any related ideas or have you already implemented this feature?

**Comment by weareoutman** [comment]
See related issue #123

**Comment by Lemon5269** [comment]
pretty nice~thank you so much!
