### ISSUE TITLE
(excluding results) Excluding results isn't working

### ISSUE THREAD

**Issue by Zenahr** [easyops-cn/docusaurus-search-local#403]
We've got some docs that we add/don't add to the sidebars.js based on the hosting location. We had thought that if docs are not part of the sidebars.js, they would not come up in search. That's not the case however.

We tried excluding the docs like so: (they live under `/docs/Controller/brand_ensto/**`

```js
ignoreFiles: ['/brand_1/', '/Controller/brand_1/', '**/brand_1/**', '/brand_1/**']
```

But this didn't work.

**Comment by weareoutman** [comment]
> If docs are not part of the sidebars.js, they would not come up in search

No, sidebars.js only declares which links do display on the sidebar.

Put regexes instead of strings for `ignoreFiles` as the README said, so try:

```js
ignoreFiles: [/\/brand_1\//, ...]
```

Note that the regexes should be URL paths instead of source file paths.
