### ISSUE TITLE
Docs not indexed if `docsRouteBasePath` is set to "/"

### ISSUE THREAD

**Issue by Lulech23** [easyops-cn/docusaurus-search-local#42]
I suppose this is half issue and half feature request. 

I prefer to use Docusaurus on a subdomain (docs.example.com) instead of a subdirectory (example.com/docs/). This is possible by setting `docs: { routeBasePath: "/" }` in `docusaurus.config.js`, but it would appear that **docusaurus-search-local** doesn't support the same routing.

A workaround I've discovered is to modify line 49 of `processDocInfos.ts` from:

```
docsRouteBasePath.some((basePath) => urlMatchesPrefix(route, basePath))
```

to:

```
(docsRouteBasePath == "" || docsRouteBasePath.some((basePath) => urlMatchesPrefix(route, basePath)))
```

This works for me since I don't need to index pages. However, this approach will break page indexing if `docsRouteBasePath` is set to root, since this condition will always return `true`. Perhaps a better solution would be to add a condition to `processPluginOptions.ts` to enable processing root paths properly instead of simply regex replacing them to empty strings.

**Comment by weareoutman** [comment]
Currently, there is a workaround for you, set `indexPages: true` in plugin options, and then the docs will be parsed as ad-hoc pages. However, It has some minor regression for the search index, such as headings are not distinguished with content.

I'll dig it deeper for a better solution when i have time.

**Comment by Lulech23** [comment]
I tried setting `indexPages: true` before based on the theory that it'd work as you described, but unfortunately I still didn't get any search results from docs.

Thanks for investigating a better solution!

**Comment by weareoutman** [comment]
Hi @Lulech23 , I just tried and `indexPages: true` seems work with `docs: { routeBasePath: "/" }`. See my testing site: https://weareoutman.github.io/my-docs-only-website/ .

Make sure you're using the latest version of this plugin.

**Comment by zxuqian** [comment]
I have the similar problem. My docusaurus site is set to blog-only mode, which blog posts are under root path. The blogs are not indexed by the plugin, but if I set `indexPages` to `true`, blogs are indexed, but all the tags pages are indexed too, and I don't want them. Any solutions for this?

**Comment by dominikmeyersap** [comment]
```
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          routeBasePath: '/',
          ...
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
  plugins: [
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        hashed: true,
        docsRouteBasePath: ['/'],
        indexBlog: false,
      },
    ],
  ],
```

Did anyone make it work to get indexed `docs` dir with `routeBasePath = /`?

**Comment by weareoutman** [comment]
try `"@easyops-cn/docusaurus-search-local": "^0.19.1"`
