### ISSUE TITLE
Duplicate URLs for search results

### ISSUE THREAD

**Issue by orhun** [easyops-cn/docusaurus-search-local#421]
See https://github.com/orhun/git-cliff/issues/693

> Searching on [git-cliff.org/docs](https://git-cliff.org/docs/) is broken.
> ### Steps To Reproduce
> 
>  1. Go to [git-cliff.org/docs](https://git-cliff.org/docs/)
> 
> 2. Search in top right corner.
> 
> 3. All results 404

**Comment by EstebanBorai** [comment]
Hi @orhun!

I experienced a similar issue after updating Docusaurus to latest versions, but having
`easyops-cn/docusaurus-search-local` in `v0.40.0`.

After updating to the following versions, it worked:

```json
"@docusaurus/core": "^3.4.0"
"@docusaurus/preset-classic": "^3.4.0"
"@easyops-cn/docusaurus-search-local": "^0.44.0"
"@docusaurus/module-type-aliases": "^3.4.0"
"@docusaurus/tsconfig": "^3.4.0"
"@docusaurus/types": "^3.4.0"
```

I think this was the first issue on this scenario: https://github.com/easyops-cn/docusaurus-search-local/issues/408

**Comment by orhun** [comment]
Thanks for the tip, works like a charm again!
