### ISSUE TITLE
Module not found: Error: Can't resolve '@generated/site-storage'

### ISSUE THREAD

**Issue by Sahillather002** [easyops-cn/docusaurus-search-local#450]
Module not found: Error: Can't resolve '@generated/site-storage'

This error is thrown when we try to add package and run.
It is throwing error for both dev and build commands.

**Comment by weareoutman** [comment]
Duplicated, see this comment https://github.com/easyops-cn/docusaurus-search-local/issues/447#issuecomment-2319624892

**Comment by yang1666204** [comment]
When I add the configuration item 
```
{
    markdown: {
        format: 'detect', // docusaurus.config.js
    },
}
```
the same error occurs.On the contrary, when I remove this configuration item, the error disappears
docusaurus v3.0.0

**Comment by yang1666204** [comment]
OK, I realized that @generated/site-storage is automatically generated in the .docusaurus directory at runtime. It should be this [pr.](https://github.com/facebook/docusaurus/pull/10121) As long as docusaurus is upgraded to a newer version, this problem can be solved.

**Comment by mackiewiczfilip** [comment]
i have same error using 3.1.0 docusaurus
