### ISSUE TITLE
Build fails on Docusaurus 2.4.3

### ISSUE THREAD

**Issue by Mikurosama** [easyops-cn/docusaurus-search-local#453]
Hi there!

First of all, thanks for such useful plugin!

Recently I've encountered a problem with my documentation instance — all attempts to build documentation with `yarn docusaurus build` command was failed with the following console messages:

```
Module not found: Error: Can't resolve '@docusaurus/useIsomorphicLayoutEffect' in 'C:\Work\Test\test\warp-docs\node_modules\@easyops-cn\docusaurus-search-local\node_modules\@docusaurus\theme-common\lib\components\Collapsible'
Module not found: Error: Can't resolve '@docusaurus/useIsomorphicLayoutEffect' in 'C:\Work\Test\test\warp-docs\node_modules\@easyops-cn\docusaurus-search-local\node_modules\@docusaurus\theme-common\lib\utils'
Module not found: Error: Can't resolve '@generated/site-storage' in 'C:\Work\Test\test\warp-docs\node_modules\@easyops-cn\docusaurus-search-local\node_modules\@docusaurus\theme-common\lib\utils'
[ERROR] Client bundle compiled with errors therefore further build is impossible.
error Command failed with exit code 1.
```

The following commands/packages are used to create my instance:
```
npx create-docusaurus@2.4.3 warp-docs test-documentation --package-manager yarn
yarn add docusaurus-plugin-openapi-docs@2.2.1
yarn add docusaurus-theme-openapi-docs@2.2.1
yarn add @easyops-cn/docusaurus-search-local@0.44.4
yarn add react@18.3.1 react-dom@18.3.1
```

What have i tried before posting this issue:
- Installation without any content
- Installation without openapi plugin
- Upgrade of plugin version to 0.44.5
- Downgrade to versions 0.44.3 and lower
- Lock cheerio version on 1.0.0-rc.12

And now i have no clues what else to try. Any help will be appreciated!

P.S. Seems like issues #447 and #450 are similar to mine.

**Comment by Mikurosama** [comment]
Oh, just in case: the same instance perfectly worked like 3 or 4 weeks ago without any changes.

**Comment by weareoutman** [comment]
Duplicated, see this comment https://github.com/easyops-cn/docusaurus-search-local/issues/447#issuecomment-2319624892
