### ISSUE TITLE
infinityfree.com detect this code as fraud 

### ISSUE THREAD

**Issue by Warsheep-GER** [easyops-cn/docusaurus-search-local#460]
The website hoster infinityfree.com detect this plugin as fraudcode. 
only thinks they can tell me are:

```
Hi there,

The only information I have is related to some redirect content

window.location.search).get("docusaurus-theme")}

present in your website theme or code.

Is it possible to remove this ?

Please let us know if there is anything we can do.
```

**Comment by weareoutman** [comment]
It's a part of code from Docusaurus, not this plugin. See https://github.com/facebook/docusaurus/blob/912c4954d9e998b49bba7f7a1303f013a9aab0b4/packages/docusaurus-theme-classic/src/inlineScripts.ts#L40

**Comment by Warsheep-GER** [comment]
then the plugin use this code too, without the searchbar the hoster worked.

**Comment by weareoutman** [comment]
No, I think this code will appear if you using the official `docusaurus-theme-classic`. You can see this code in the page source of https://docusaurus.io/

**Comment by Warsheep-GER** [comment]
without searchbar all is fine, with the searchbar it got detected, but the hoster dosnt give me more info as the codesnipped bec. they will not share how the fraud detection work :/

**Comment by weareoutman** [comment]
Then I guess their report is actually not related to the code at `window.location.search).get("docusaurus-theme")}`.

First confirm that the page source of your site without the search plugin, does it contain that code or not.

If it contains that code, but their report is fine, then you should ask them for the actual cause of their report.
