### ISSUE TITLE
Question: clearing highlights/clearing past searches

### ISSUE THREAD

**Issue by scottweitzner** [easyops-cn/docusaurus-search-local#48]
I notice that when i'm done with my search there is no way to clear my search highlights. Furthermore I noteicce that if you have multiple searches on the same doc, the prior search's highlights remain. 

For instance if I search the phrase "invoke" and choose a hit on the page `docs/mydoc` and then search "in" and choose the same doc all instances of both "invoke" and "in" will be highlighted. 

It'd be helpful to have highlights cleared between searches as well as manually if I want to share a link with my colleague sans highlights. 

Is this a feature that exists but is not documented?

**Comment by weareoutman** [comment]
Hi, this is fixed in v0.14.4. Highlights will be cleared between searches now.

And if you want to manually clear highlights, just remove the params like `?_highlight=x` in your browser URL.

**Comment by scottweitzner** [comment]
you work fast. thanks mate

**Comment by tobiasbueschel** [comment]
Hi @weareoutman,

thanks for the clarification. What do you think about adding `ESC` as a keyboard shortcut to clear highlights similar to how Chrome's native search `CMD` + `F` functionality works (that is if you are on macOS)?

This could also be extended with a toggle to jump between search results?
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/13087421/164764239-c80860eb-5b71-4e0f-8838-d5c29e32465c.png">
