### ISSUE TITLE
Provide a way to customize default search text like "No results", "See all results" etc.

### ISSUE THREAD

**Issue by sethyuan** [easyops-cn/docusaurus-search-local#59]
Congrats, this plugin is awesome! However it could be better if you can provide a way to customize default text, i.e. if I use Chinese search support (because the docs are mainly in Chinese) I'd like to see "See all results" in Chinese too.

**Comment by weareoutman** [comment]
Hi this feature was released in v0.15.0, check the [docs here](https://github.com/easyops-cn/docusaurus-search-local#translations).
