### ISSUE TITLE
Hitting Enter Key after search string entered causes page to fail

### ISSUE THREAD

**Issue by mocon11** [easyops-cn/docusaurus-search-local#64]
When you type in the search string, the search works, but if you then hit the enter key (Which a lot of people do by default) the page faults to 'This page isn't working'.
Is there a fix or workaround for this other than (Don't hit the enter key)

**Comment by weareoutman** [comment]
I can't reproduce this issue, could you please describe how to reproduce it?

**Comment by mocon11** [comment]
Thanks for the response.
I can type in the string I want to search for ('Document' for example).  If I do not hit the return key I get a full search of the site with the word 'document' as expected and I can select any one of these and it works perfectly.  However when I hit the enter key after putting in the search string 'document' the results page will then return 'This page isn't working' ERR_TOO_MANY_REDIRECTS...
In the address bar for the webpage it keeps appending a / to the search.

https://WEBSITENAMEREMOVED/search?q=document//////////////////////////////////////////////////////


We can add some verbage to the search to say not to hit the enter key, but if this can be fixed, I would rather do that.

**Comment by weareoutman** [comment]
Um, this maybe a browser compatibility issue, I can't reproduce it on the [example site](https://easyops-cn.github.io/docusaurus-search-example/) using Chrome v89 and Safari v14 on my Mac. What's your os system and browser?

**Comment by weareoutman** [comment]
Try v0.15.1

**Comment by mocon11** [comment]
**This is the config of our usage.  Have I missed anything?**
  plugins: [ 
    [require.resolve("@easyops-cn/docusaurus-search-local"), {
      highlightSearchTermsOnTargetPage: true,
      indexPages: false,
      indexDocs: true,
      indexBlog: true,
      docsRouteBasePath: ["docs/cloud-hosting", "docs/collaboration", "docs/virtual-server", "docs/kubernetes", "docs/open-shift", "docs/database", "docs/windows-provisioning",  "docs/mac-provisioning", "docs/file-transfer",
        "docs/IaC", "docs/job-control", "docs/loggging", "docs/middleware", "docs/networking", "docs/security", "docs/storage", "docs/contact-us", "docs/faq", "docs/process-guidelines",
        "docs/resources", "docs/faq", "docs/professional-services", "docs/iam/directory", "docs/iam/cryptographic-services", "docs/iam/hs-id", "docs/iam/miscellaneous", "docs/iam/one-healthcare-id",
        "release-notes", "docs/big-data"
      ],
      hashed: true,
    }]
