### ISSUE TITLE
Version support

### ISSUE THREAD

**Issue by Farrser** [easyops-cn/docusaurus-search-local#66]
It would be good if we could have version support, or at least a way of not indexing all versions. Currently results are shown for all versions resulting in duplicate search results for each version in the docs.

**Comment by gtnardy** [comment]
I experienced same problem as well!

**Comment by Farrser** [comment]
I've started a draft PR which now has a working versioned search in it #116 

I've not yet tested to see if it still works with non-versioned sites

**Comment by ihack2712** [comment]
Any progress on this?

**Comment by nascode** [comment]
This is a missing feature for docs site with many versioned docs. Since the original plugin https://github.com/cmfcmf/docusaurus-search-local has supported multi version already, maybe the maintainer can try to look at it.

**Comment by sebaplaza** [comment]
Same problem here.

Any news ?

Thanks for your PR @Farrser  !

**Comment by Beluk** [comment]
Are there any plans that this would be supported in future?
I would love to see that feature.

**Comment by weareoutman** [comment]
This is just launched in v0.27.0, thanks to @Cyriuz's work 🎉
