### ISSUE TITLE
index language pt fail

### ISSUE THREAD

**Issue by rafaelrdealmeida** [easyops-cn/docusaurus-search-local#9]
Hello congratulations for the work!

I'm having trouble indexing words in Portuguese(pt). For example, words like "introdução", "documentação" are not found. I believe the problem is in recognizing characters such as ç ã

docusaurus.config.js

![Captura de tela de 2020-10-28 16-29-37](https://user-images.githubusercontent.com/18035347/97487990-69e0bb80-193c-11eb-8582-fef70985f1b8.png)

DEBUG=search-local:* yarn build

![Captura de tela de 2020-10-28 16-28-45](https://user-images.githubusercontent.com/18035347/97487991-6b11e880-193c-11eb-99c3-07c0c2450383.png)

**Comment by weareoutman** [comment]
Oops, yes, it currently can't recognize characters other than letters in Latin alphabet and Chinese. I will try to fix it today.

**Comment by weareoutman** [comment]
Hi, just fixed and published v0.9.3. Please try it and feel free to reopen this issue if the problem persists.

**Comment by rafaelrdealmeida** [comment]
Hello, I tested it here and it's working perfectly, thanks!

otherwise, are there any limitations on the number of characters or words that you type in the search box?

For example, when typing

"Documentação interna do" the term found, but if you put the next word ("Documentação interna do Labri" there is no return of result

**Comment by weareoutman** [comment]
I don't known Portuguese at all, so I need some knowledge:

- Is `Labri` a full word or a partial of word?
- Is `Labri` an inflection or a derivation word from a root word?
- Or itself is a root word?

**Comment by rafaelrdealmeida** [comment]
Hi, labri is an acronym

if possible see:

- [Labri/UNESP iDOCS](https://idocs.labriunesp.org/)
- [LabRI/UNESP - Gitlab](https://gitlab.com/unesp-labri/docs/idocs)

**Comment by weareoutman** [comment]
OK, I just figured out the problem is caused by the stop word `do` in "Documentação interna do Labri".

Stop words will be removed from the search index, but currently they are not removed from the search keyword. I'll try to refine it today.

By the way, "Documentação interna do" works because the last word is considered a _word-that-is-typing_, so the `do` is also matching `do*`.

**Comment by weareoutman** [comment]
Hi, again, published v0.10.1, which is supposed to fix your issue.

**Comment by rafaelrdealmeida** [comment]
Hello, it's working perfectly, thanks!
