### ISSUE TITLE
highlightSearchTermsOnTargetPage in Code blocks only works if page already selected

### ISSUE THREAD

**Issue by donkaes** [easyops-cn/docusaurus-search-local#92]
This can be reproduced in the Live Demo:
https://easyops-cn.github.io/docusaurus-search-example/docs

If you search for _Python_ the highlighting only works if the page "Style Guide" was selected. If you select the page "Document Number 2" and do the search, the term is not highlighted.

**Comment by weareoutman** [comment]
Does it only happen with words in code blocks? This is probably caused by that code being rendered after search term highlighting.

**Comment by donkaes** [comment]
I have seen this problem only in code blocks. Yes, seems that the code
syntax highlighting is done after the search term highlighting.

Am Do., 3. Juni 2021 um 11:02 Uhr schrieb Shenwei Wang <
***@***.***>:

**Comment by weareoutman** [comment]
There is a workaround to fix it, and released in v.018.1
