### ISSUE TITLE
The search plugins can't search the sub directory when enable docs only mode.

### ISSUE THREAD

**Issue by Avimitin** [easyops-cn/docusaurus-search-local#97]
I have documents structure like below:

```text
docs\
    |-subdirectory\
        |-some-document.md
    |-introduction.md
```

And I enable this setting at docusaurus.config.js:

```js
docs: {
  sidebarPath: require.resolve("./sidebars.js"),
  path: "./docs",
  routeBasePath: "/",
},
blog: false,
```
The plugin can only search those documents which locate at the root path. The plugin can't search content inside the subdirectory.

I found a solution that set all the subdirectories into the `docsRouteBasePath` array. The plugin will still work well. But it is hard to maintain when I have plenty of subdirectories. If the plugins can search identifiers recursively into all the subdirectories it will be more convenient.

**Comment by Avimitin** [comment]
Seems like [the solution](https://github.com/easyops-cn/docusaurus-search-local/issues/42#issuecomment-751472182) in #42 which set `indexPages: true` could works. But it is too magic. If the plugin can add a new setting like `docsOnly: true` it will be more convenient.

**Comment by weareoutman** [comment]
Yes, this is duplicated with #42, please track this issue there instead. And by the way, currently I have limited time to dig it deeper to fix it.

**Comment by weareoutman** [comment]
try `"@easyops-cn/docusaurus-search-local": "^0.19.1"`
